spring.application.name=FixMyStreet
server.port = 8080

spring.data.mongodb.uri = mongodb://localhost:27017/fixmystreet



spring.mail.host = smtp.gmail.com
spring.mail.port = 587

spring.mail.username =jd2115official@gmail.com
spring.mail.password =ekjcjguguggdpyrf

spring.mail.properties.mail.smtp.auth  = true

spring.mail.properties.mail.smtp.starttls.enable=true


jwt.secret=FixMyStreetSecretKeyForJwtAuthentication2026FixMyStreet
jwt.expiration=86400000



cloudinary.cloud-name=doonfwjwt
cloudinary.api-key=236674888386386
cloudinary.api-secret=bEcLVBC6ptrO-zEMbpQiRCPWFvQ
